# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_my_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatinship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('followed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='My_User',
        ),
    ]
