# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170324_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatinship',
            old_name='followed_from',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='relatinship',
            old_name='followed_to',
            new_name='follower',
        ),
    ]
